version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/core"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/node"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/api"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
