language: rust
sudo: false

matrix:
  include:
    - rust: 1.21.0
    - rust: stable
    - os: osx
    - rust: beta
    - rust: nightly

    - rust: nightly
      before_script:
        - pip install 'travis-cargo<0.2' --user && export PATH=$HOME/.local/bin:$PATH
      script:
        - cargo doc --no-deps --all-features
      after_success:
        - travis-cargo --only nightly doc-upload

script:
  - cargo test

env:
  global:
    secure: "jzqfkE1zPzwe/ofghiKvN/3Vo/kLYN+pDzSIOGL3Xnum5eayUf87Uae1UuAbgXfKm2/meXWizMjcVrBeNrfxRi3qvaM+MLGAR4YK4G2Z91Uuf3edHF/uu7rhhaLWsPOkb4qDH/lBRIsKhDMpLXuc/5DSqZdPVQa8H+5ULtQFwWkets8BGfPu+vCgHeGb/lMgm56BnedUBqO7hAI1dYEn55R3L4rwgkMDWTyiAczL3RBuFJrHIAY5C+8JbkvvL+4+9v3oulJgXDQnQYkdNiZE0BjCvj+w0J2W1C1E8vgX3wB71RbQ+ijh1f98RoR6SqDqWE5eZDrl+L8V3sP2BIK/yhCrUCwpysQXW6Lo9/aVEDVPTB2KxvVjGb9jFwYyvZLuB0Q1t7UlOIo3MXIZLvMSZT99tfOZ5f1MdQt0C+ACZ6LKTAF0VUxmEGequ8kBBj+uDnHiIeWzkCJVTpqwTuJcprEPNCUx6T2pxyIZkyTS2DzviBbzLE/fLahm/+RJrkraH3lD4tLiTC7IckNrmnufx78oIsbYxdYp4Bo5cASLiRTVL9BS3yJ5So/Qr/C5pQ48PjKokyBDXX01U9SA6K3nxJ5tO+/q4d77utSaG9kb1UQpwNojpMBTBC1OFVbb/2nlOmf2BKLpciNCBmUHJnq/+By9l0f0eRS/0JanFBdIDkM="

notifications:
  email:
    on_success: never
