name: docs

env:
  RUST_BACKTRACE: 1

jobs:
  docsrs:
    name: cargo doc --cfg docsrs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: nightly
    - uses: actions-rs/cargo@v1
      with:
        command: rustdoc
        toolchain: nightly
        args: --all-features --locked -- --cfg=docsrs -Dwarnings

on:
  push:
    branches: [staging, trying]
