name: updates

env:
  RUST_BACKTRACE: 1

jobs:
  update:
    name: cargo build --update
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: hecrj/setup-rust-action@v1
    - uses: actions-rs/cargo@v1
      with:
        command: update
        args: --aggressive
    - uses: actions-rs/cargo@v1
      with:
        command: test
        args: --workspace --locked --all-features

on:
  push:
    branches: [staging, trying]
  schedule:
  - cron: '0 0 * * 5'
