[package]
name = "dao"
version = "0.1.0"
authors = ["Jacque Antoine DeGraff <jacquedegraff@creodamo.com>"]
edition = "2021"

[dependencies]
serde = "1.0"
serde_json = "1.0"

[dev-dependencies]
serde = { version = "1.0", features = ["derive"] }
