name: Approx CI build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check-fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check formatting
        run: cargo fmt -- --check
  build-latest:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -D warnings
    steps:
      - uses: actions/checkout@v2
      - run: cargo build --no-default-features;
      - run: cargo build;
      - run: cargo build --features num-complex;
      - name: Run tests
        run: cargo test;
  build-1-31-0:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -D warnings
    steps:
      - name: Install stable-2021-12-04
        uses: actions-rs/toolchain@v1
        with:
          toolchain: "1.31.0"
          override: true
      - uses: actions/checkout@v2
      - run: cargo build --no-default-features;
      - run: cargo build;
      - run: cargo build --features num-complex;
      - name: Run tests
        run: cargo test;
  build-no-std:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -D warnings
    steps:
      - uses: actions/checkout@v2
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - name: install xargo
        run: cp .github/Xargo.toml .; rustup component add rust-src; cargo install -f xargo;
      - name: build x86_64-unknown-linux-gnu
        run: xargo build --verbose --no-default-features --target=x86_64-unknown-linux-gnu;
