language: rust

# Test on the latest versions of all channels.
rust:
  - stable
  - beta
  - nightly

script:
  - cargo build --all
  - cargo test --all

# Run this build on the "container-based infrastructure"
# See http://docs.travis-ci.com/user/workers/container-based-infrastructure/.
sudo: false
