name: QuantumFuse CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        language: [rust, go, python, node]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Rust
      if: matrix.language == 'rust'
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true

    - name: Build with Cargo
      if: matrix.language == 'rust'
      run: cargo build --verbose

    - name: Run tests with Cargo
      if: matrix.language == 'rust'
      run: cargo test --verbose

    - name: Set up Go
      if: matrix.language == 'go'
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build with Go
      if: matrix.language == 'go'
      run: go build ./...

    - name: Run tests with Go
      if: matrix.language == 'go'
      run: go test ./...

    - name: Set up Python
      if: matrix.language == 'python'
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      if: matrix.language == 'python'
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests with Pytest
      if: matrix.language == 'python'
      run: pytest

    - name: Set up Node.js
      if: matrix.language == 'node'
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      if: matrix.language == 'node'
      run: npm install

    - name: Run tests with Jest
      if: matrix.language == 'node'
      run: npm test
